server:
  port: 8080

spring:
  application:
    name: gym-crm-prod
  profiles:
    active: default

  datasource:
    username: sa
    password: s3cr3t
    url: jdbc:postgresql://localhost:5432/gymcrm
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:host.docker.internal:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
        spring.json.value.default.type: com.epam.contracts.events.TrainingEvent

app:
  topics:
    training: trainer-training-events

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

security:
  bruteforce:
    max-attempts: 3
    block-minutes: 5

  jwt:
    secret: ${JWT_SECRET:'this-is-a-very-long-32+chars-secret-key!!'}
    issuer: gym-crm
    access-token-minutes: 30

  cors:
    3allowed-origins: "https://app.gym-crm.com"

logging:
  level:
    root: WARN
    com.epam.gymcrm: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: when_authorized
  prometheus:
    metrics:
      export:
        enabled: true

feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 3000

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: TIME_BASED
        slidingWindowSize: 60 # saniye
        minimumNumberOfCalls: 20
        permittedNumberOfCallsInHalfOpenState: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        slowCallDurationThreshold: 1s
        slowCallRateThreshold: 50
        waitDurationInOpenState: 10s
        recordExceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.HttpServerErrorException
        ignoreExceptions:
          - com.epam.gymcrm.domain.exception.NotFoundException
    instances:
      workload:
        baseConfig: default

  retry:
    instances:
      workload:
        maxAttempts: 3
        waitDuration: 200ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 1.5
        exponential-max-wait-duration:
          seconds:  2s
        failAfterMaxAttempts: true
        retryExceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.HttpServerErrorException
        ignoreExceptions:
          - com.epam.gymcrm.domain.exception.NotFoundException